### ISSUE TITLE
Yet another crash bug

### ISSUE THREAD

**Issue by GoldenretriverYT** [GOOMBAServer/GOOMBAServer#5]
**Describe the bug**
This bug crashes GOOMBAServer.

**To Reproduce**
Create a file and view it with this connect:
```
->GOOMBATIME<-
CONNECT:
->STOPITGOOMBA<-
```

**Expected behavior**
Print error and continue execution.

**Comment by GoldenretriverYT** [comment]
@GoombaProgrammer pls fix very threatining problem

**Comment by GoombaProgrammer** [comment]
Thanks for finding this bug, I will fix it in the next commit!
